library(XML)
doc<-xmlTreeParse("pubmed.xml",useInternalNodes=T)
top<-xmlRoot(doc)
nodes=getNodeSet(top,"//MedlineCitation/MeshHeadingList")
mesh_data<-lapply(nodes, function(x) xmlSApply(x, xmlValue))
mat2<-c(unlist(mesh_data),ncol=1)
frq<-table(mat2)
sfrq<-sort(frq,decreasing=T)
names_mesh<-sub("[[:punct:]]","",names(sfrq))
tab_clean<-cbind(names_mesh,sfrq)
save(tab_clean,file="nature_analysis.Rdata")
